SELECT ROUND((SUM(DECODE(D.ORDER_DATE, D.CUSTOMER_PREF_DELIVERY_DATE, 1, 0)) / COUNT(D.CUSTOMER_ID)) * 100, 2) AS IMMEDIATE_PERCENTAGE
FROM (
    SELECT CUSTOMER_ID, MIN(ORDER_DATE) ORDER_DATE
    FROM DELIVERY
    GROUP BY CUSTOMER_ID
) F, DELIVERY D
WHERE 1=1
AND D.CUSTOMER_ID = F.CUSTOMER_ID
AND D.ORDER_DATE = F.ORDER_DATE;
