SELECT TO_CHAR(TO_DATE(TRANS_DATE, 'YYYY-MM-DD'), 'YYYY-MM') MONTH, COUNTRY, COUNT(ID) TRANS_COUNT
, SUM(DECODE(STATE, 'approved', 1, 0)) APPROVED_COUNT
, SUM(AMOUNT) TRANS_TOTAL_AMOUNT
, SUM(DECODE(STATE, 'approved', AMOUNT, 0)) APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(TO_DATE(TRANS_DATE, 'YYYY-MM-DD'), 'YYYY-MM'), COUNTRY
ORDER BY TO_CHAR(TO_DATE(TRANS_DATE, 'YYYY-MM-DD'), 'YYYY-MM'), COUNTRY DESC;
