SELECT NAME FROM EMPLOYEE WHERE ID IN (
    SELECT MANAGERID FROM (
        SELECT MANAGERID, COUNT(ID) MANAGERCOUNT
        FROM EMPLOYEE
        GROUP BY MANAGERID
        HAVING COUNT(ID) >= 5
    )
);
