WITH ID AS (
SELECT ID, VISIT_DATE, PEOPLE, PRE_ID, POST_ID
FROM (
    SELECT ID, VISIT_DATE, PEOPLE
    , LAG(ID) OVER (ORDER BY ID) PRE_ID
    , LEAD(ID) OVER (ORDER BY ID) POST_ID
    FROM (
        SELECT ID, VISIT_DATE, PEOPLE
        FROM STADIUM
        WHERE PEOPLE >= 100
    )
)
WHERE ID + 1 = POST_ID AND PRE_ID + 1 = ID
)

SELECT ID, TO_CHAR(VISIT_DATE, 'YYYY-MM-DD') VISIT_DATE, PEOPLE 
FROM STADIUM
WHERE 1=1
AND (ID IN (SELECT PRE_ID FROM ID) OR ID IN (SELECT POST_ID FROM ID) OR ID IN (SELECT ID FROM ID))
ORDER BY ID;
